### ISSUE TITLE
Subprocess.py File Not Found

### ISSUE THREAD

**Issue by Anonymous2** [aviupadhyayula/viewbot#1]
Hello, when I try to make it work it throws some errors, first one was executable_path=driverpath
so I removed that part of code as was suggested in the readme file.
Then I tried adding other options suggested in the Replit section, and it thrown errors anyway.
I tried then with executable_path=driverpath present but no options added, and it says subprocess.py file not found.

Can you correct the repository to work "as is" for local?

**Comment by aviupadhyayula** [comment]
Sorry to hear about the issues you ran into. Do you mind attaching a screenshot or copy-pasting the error message you're receiving on your local device? 

It sounds like you might've installed the wrong version of chromedriver — you need to make sure that it corresponds to your version of Google Chrome. Alternatively, you might've left your chromedriver file outside of the folder the script is in — make sure that both the chromedriver file and viewbot.py are in the same folder.

**Comment by Anonymous2** [comment]
Thanks for your reply. Ok with latest chrome driver it starts, but doesn't work for my use. At each connection attempted it says usb_device_handle_win.cc: 1048 failed to read descriptor from node connection: a device connected to the system is no longer working. (0x1F).

I'm trying it as a viewbot for twitch, it isn't the intended usage or it's a proxy problem?

Maybe it will work as a viewbot for facebook live?

**Comment by aviupadhyayula** [comment]
The script isn't supposed to be used as a persistent viewbot (i.e. it's supposed to open a page with a proxy and then close the tab on-load). Given that limitation, it probably won't work for Facebook Live or Twitch. 

You could try tweaking the code and removing the `driver.quit()` command on line 66, but if you're after a Twitch viewbot I'd suggest looking elsewhere.

The `usb_device_handle_win.cc` error sounds like it's due to a faulty USB device. Check out [this post](https://stackoverflow.com/questions/65080685/usb-usb-device-handle-win-cc1020-failed-to-read-descriptor-from-node-connectio "https://stackoverflow.com/questions/65080685/usb-usb-device-handle-win-cc1020-failed-to-read-descriptor-from-node-connection") for more details.

**Comment by Anonymous2** [comment]
Okay, thanks.
